# NumPy Basics
このノートブックでは、NumPyの基本操作について説明します。

## 1. 配列の作成

In [1]:
import numpy as np

# 配列の作成
array = np.array([1, 2, 3, 4, 5])
zeros_array = np.zeros((2, 3))
ones_array = np.ones((3, 3))
range_array = np.arange(0, 10, 2)

print("Array:", array)
print("Zeros Array:", zeros_array)
print("Ones Array:", ones_array)
print("Range Array:", range_array)

Array: [1 2 3 4 5]
Zeros Array: [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Range Array: [0 2 4 6 8]


## 2. 配列の基本操作

In [2]:
# 配列のスライシング
array = np.array([1, 2, 3, 4, 5])
print("Original Array:", array)
print("First 3 elements:", array[:3])

# 配列の要素の変更
array[0] = 10
print("Modified Array:", array)

Original Array: [1 2 3 4 5]
First 3 elements: [1 2 3]
Modified Array: [10  2  3  4  5]


## 3. 配列の形状変更

In [3]:
# 配列の形状変更
array = np.arange(1, 10)
reshaped_array = array.reshape(3, 3)
print("Original Array:", array)
print("Reshaped Array (3x3):\n", reshaped_array)

Original Array: [1 2 3 4 5 6 7 8 9]
Reshaped Array (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


## 4. 数学的計算

In [4]:
# 配列の平均、和、最大値・最小値
array = np.array([1, 2, 3, 4, 5])
print("Array:", array)
print("Mean:", np.mean(array))
print("Sum:", np.sum(array))
print("Max:", np.max(array))
print("Min:", np.min(array))

Array: [1 2 3 4 5]
Mean: 3.0
Sum: 15
Max: 5
Min: 1


## 5. 行列演算

In [5]:
# 行列の作成
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# 行列の積
product = np.dot(matrix1, matrix2)

# 行列の逆行列
inverse = np.linalg.inv(matrix1)

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Matrix Product:\n", product)
print("Inverse of Matrix 1:\n", inverse)

Matrix 1:
 [[1 2]
 [3 4]]
Matrix 2:
 [[5 6]
 [7 8]]
Matrix Product:
 [[19 22]
 [43 50]]
Inverse of Matrix 1:
 [[-2.   1. ]
 [ 1.5 -0.5]]
